# example netlify.toml
[build]
  command = "yarn build"
  functions = "functions"
  publish = "public"
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  #[dev] 
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 

[[redirects]]
  from = "/wp-admin"
  to = "/nicetry"
  status = 301
  force = true

[[redirects]]
  from = "/wp-json"
  to = "/nicetry"
  status = 301
  force = true

[[redirects]]
  from = "/admin"
  to = "/nicetry"
  status = 301
  force = true

[[redirects]]
  from = "/wp-login"
  to = "/nicetry"
  status = 301
  force = true

[[redirects]]
  from = "/principles"
  to = "/nicetry"
  status = 301
  force = true

[[redirects]]
from = "/env"
  to = "/nicetry"
  status = 301
  force = true

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]
  
  # required config
  checkPaths = ['/'] # you can give an array of directories or paths to html files, that you want to run a11y checks on
  
  # optional config
  resultMode = "warn" # is "error" by default 
  
  # Developer only
  debugMode = true # extra logging for plugin developers